name: google_maps_drawing_tools
description: A Flutter plugin that adds drawing tools (polygons, circles, rectangles) on Google Maps, enabling users to interactively draw and edit shapes within a Flutter application.
version: 0.0.5
homepage: https://github.com/ExploreAritra/google_maps_drawing_tools
repository: https://github.com/ExploreAritra/google_maps_drawing_tools

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.1
  collection: ^1.19.1
  geolocator: ^14.0.0
  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0